[raylib-linux]
arch = "x86_64"
os = "linux"
lazy = true
git-tree-sha1 = "ba6fefde09a27f3b1bc714cdaa8712c141ad79c2"

    [[raylib-linux.download]]
    url = "https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_linux_amd64.tar.gz"
    sha256 = "3d95ef03d5b38dfa55c0a16ca122d382134b078f0e5b270b52fe7eae0549c000"

[raylib-macos]
arch = "x86_64"
os = "macos"
lazy = true
git-tree-sha1 = "404d4bd22115288fa16084c386fbaf7dfa236d77"

    [[raylib-macos.download]]
    url = "https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_macos.tar.gz"
    sha256 = "930c67b676963c6cffbd965814664523081ecbf3d30fc9df4211d0064aa6ba39"

